Repository GeoNodeUserGroup-DE/geonode-k8s, pull requests merged in 2023-11, with the labels that each got.

#115 Bugfix bool string confusion in lockdown variable
  charts/geonode/values.yaml
Labels: bug, 1.1.0

#113 Allow definition of additional CORS origin for nginx configuration
  charts/geonode/README.md
  charts/geonode/templates/nginx/nginx-conf.yaml
  charts/geonode/values.yaml
Labels: documentation, feature, 1.1.0

#110 Make ingress annotations configurable
  README.md
  charts/geonode/Chart.yaml
  charts/geonode/README.md
  charts/geonode/templates/nginx/nginx-ingress.yaml
  charts/geonode/values.yaml
  docs/nginx-ingress-class.md
Labels: enhancement, feature, 1.1.0
