Repository GeoNodeUserGroup-DE/geonode-k8s, pull requests merged in 2023-09, with the labels that each got.

#65 Issue#59 task prepare this repository to be available on artifact hub
  .github/workflows/helm-lint-check.yaml
  .github/workflows/release.yaml
  .gitignore
  .pre-commit-config.yaml
  README.md
  charts/geonode/.gitignore
  charts/geonode/.helmignore
  charts/geonode/Chart.yaml
  charts/geonode/README.md
  charts/geonode/templates/.gitignore
  charts/geonode/templates/NOTES.txt
  charts/geonode/templates/_helpers.tpl
  charts/geonode/templates/geonode/geonode-deploy.yaml
  charts/geonode/templates/geonode/geonode-entrypoint-sh-conf.yaml
  charts/geonode/templates/geonode/geonode-env.yaml
  charts/geonode/templates/geonode/geonode-favicon.yaml
  charts/geonode/templates/geonode/geonode-fixtures.yaml
  charts/geonode/templates/geonode/geonode-local-settings.yaml
  charts/geonode/templates/geonode/geonode-pvc.yaml
  charts/geonode/templates/geonode/geonode-svc.yaml
  charts/geonode/templates/geonode/geonode-tasks-py-conf.yaml
  charts/geonode/templates/geonode/geonode-uwsgi-ini-conf.yaml
  charts/geonode/templates/geoserver/geoserver-deploy.yaml
  charts/geonode/templates/geoserver/geoserver-env.yaml
  charts/geonode/templates/geoserver/geoserver-notifier-xml.yaml
  charts/geonode/templates/geoserver/geoserver-svc.yaml
  charts/geonode/templates/nginx/nginx-conf.yaml
  charts/geonode/templates/nginx/nginx-deploy.yaml
  charts/geonode/templates/nginx/nginx-ingress.yaml
  charts/geonode/templates/nginx/nginx-svc.yaml
  charts/geonode/templates/postgres/geonode-manifest.yaml
  charts/geonode/templates/postgres/postgres-external-geodata-secrets.yaml
  charts/geonode/templates/postgres/postgres-external-geonode-secrets.yaml
  charts/geonode/templates/postgres/postgres-external-postgres-secrets.yaml
  charts/geonode/values.yaml
  deployment/geonode/Chart.yaml
  docs/access-geonode-database-from-outside.md
  docs/external-database-access.md
  docs/external-database.md
  docs/minikube-installation.md
  docs/nginx-ingress-class.md
Labels: documentation, enhancement

#68 Issue#27 py csw single microservice
  charts/geonode/templates/_helpers.tpl
  charts/geonode/templates/geonode/geonode-env.yaml
  charts/geonode/templates/geonode/geonode-favicon.yaml
  charts/geonode/templates/nginx/nginx-conf.yaml
  charts/geonode/templates/pycsw/pycsw-cfg.yaml
  charts/geonode/templates/pycsw/pycsw-deploy.yaml
  charts/geonode/templates/pycsw/pycsw-env.yaml
  charts/geonode/templates/pycsw/pycsw-mappings-py.yaml
  charts/geonode/templates/pycsw/pycsw-svc.yaml
  charts/geonode/values.yaml
  docs/pycsw.md
  minikube-values.yaml
Labels: enhancement, feature

#71 Provide confidential values as secret
  charts/geonode/README.md
  charts/geonode/templates/_helpers.tpl
  charts/geonode/templates/geonode/geonode-deploy.yaml
  charts/geonode/templates/geonode/geonode-env.yaml
  charts/geonode/templates/geonode/geonode-secret.yaml
  charts/geonode/templates/geoserver/geoserver-deploy.yaml
  charts/geonode/templates/geoserver/geoserver-env.yaml
  charts/geonode/templates/geoserver/geoserver-secret.yaml
  charts/geonode/templates/postgres/postgres-external-geodata-secrets.yaml
  charts/geonode/templates/postgres/postgres-external-geonode-secrets.yaml
  charts/geonode/templates/postgres/postgres-external-postgres-secrets.yaml
  charts/geonode/templates/postgres/postgresql-operator.yaml
  charts/geonode/values.yaml
  docs/provide-custom-secret.md
  minikube-values-external-db.yaml
  minikube-values.yaml
Labels: documentation, feature

#74 release 1.0.0 final changes [geonode 4.1.2]
  README.md
  charts/geonode/Chart.yaml
  charts/geonode/README.md
  charts/geonode/templates/geonode/geonode-deploy.yaml
  charts/geonode/values.yaml
  minikube-values.yaml
Labels: bug, enhancement

#76 Issue#72 bug celery container is not starting properly and exiting right away
  README.md
Labels: documentation

#78 fixing release build
  .github/workflows/release.yaml
Labels: bug

#83 FIxes #81
  charts/geonode/templates/pycsw/pycsw-deploy.yaml
Labels: 1.0.1

#84 Issue#82 bug cannot enable ldap support
  charts/geonode/templates/geonode/geonode-local-settings.yaml
Labels: bug, 1.0.1

#85 release 1.0.1
  README.md
  charts/geonode/Chart.yaml
  charts/geonode/README.md
Labels: 1.0.1

#90 [Fixes #88] Geoserver cannot connect to Database
  charts/geonode/templates/geoserver/geoserver-env.yaml
Labels: bug, 1.1.0, 1.0.2

#92 1.0.2
  README.md
  charts/geonode/Chart.yaml
  charts/geonode/README.md
Labels: 1.0.2

#100 release 1.0.3 updated geonode version to 4.1.3
  README.md
  charts/geonode/Chart.yaml
  charts/geonode/README.md
  charts/geonode/values.yaml
Labels: documentation, 1.0.3
