Repository GeoNodeUserGroup-DE/geonode-k8s, pull requests merged in 2023-08, with the labels that each got.

#43 gh action to check template linting
  .github/workflows/helm-lint-check.yaml
Labels: enhancement, good first issue

#44 added templates for issues and pull requests
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/task_docs_others.md
  .github/pull_request_template.md
Labels: enhancement

#47 [Fixing #8] External PostgreSQL Database support
  README.md
  deployment/geonode/templates/_helpers.tpl
  deployment/geonode/templates/geonode/geonode-deploy.yaml
  deployment/geonode/templates/geonode/geonode-entrypoint-sh-conf.yaml
  deployment/geonode/templates/geonode/geonode-env.yaml
  deployment/geonode/templates/geonode/geonode-tasks-py-conf.yaml
  deployment/geonode/templates/geoserver/geoserver-deploy.yaml
  deployment/geonode/templates/geoserver/geoserver-env.yaml
  deployment/geonode/templates/geoserver/geoserver-svc.yaml
  deployment/geonode/templates/postgres/geonode-manifest.yaml
  deployment/geonode/templates/postgres/postgres-external-geodata-secrets.yaml
  deployment/geonode/templates/postgres/postgres-external-geonode-secrets.yaml
  deployment/geonode/templates/postgres/postgres-external-postgres-secrets.yaml
  deployment/geonode/values.yaml
  docs/access-geonode-database-from-outside.md
  docs/external-database.md
  minikube-values-external-db.yaml
Labels: feature

#57 Issue#56 ensure helm docs has been run before commit
  .pre-commit-config.yaml
  README.md
Labels: documentation, enhancement
